//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetlibApi1.XMLLicenseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://secure.softwarekey.com/solo/webservices/", ConfigurationName="XMLLicenseService.XmlLicenseServiceSoap")]
    public interface XmlLicenseServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateCheck(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateCheckAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateCheckS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateCheckS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateCheckS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateCheckSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/InfoCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode InfoCheck(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/InfoCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InfoCheckAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/InfoCheckS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode InfoCheckS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/InfoCheckS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InfoCheckSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/ValidateRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValidateRegistration(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/ValidateRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValidateRegistrationAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/ValidateRegistrationS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ValidateRegistrationS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/ValidateRegistrationS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ValidateRegistrationSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Register(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RegisterAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/RegisterS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode RegisterS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/RegisterS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RegisterSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateRegistration(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateRegistrationAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateRegistrationS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateRegistrationS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateRegistrationS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateRegistrationSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode Add(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/AddS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode AddS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/AddS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateActivationFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateActivationFields(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateActivationFields", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateActivationFieldsAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateUserDefinedFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateUserDefinedFields(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateUserDefinedFields", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateUserDefinedFieldsAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateUserDefinedFieldsS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateUserDefinedFieldsS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateUserDefinedFieldsS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateUserDefinedFieldsSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/GetLicenseCustomData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLicenseCustomData(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/GetLicenseCustomData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLicenseCustomDataAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/GetLicenseCustomDataS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetLicenseCustomDataS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/GetLicenseCustomDataS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLicenseCustomDataSAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateLicenseCustomData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateLicenseCustomData(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateLicenseCustomData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateLicenseCustomDataAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateLicenseCustomDataS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode UpdateLicenseCustomDataS(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://secure.softwarekey.com/solo/webservices/UpdateLicenseCustomDataS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateLicenseCustomDataSAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlLicenseServiceSoapChannel : NetlibApi1.XMLLicenseService.XmlLicenseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlLicenseServiceSoapClient : System.ServiceModel.ClientBase<NetlibApi1.XMLLicenseService.XmlLicenseServiceSoap>, NetlibApi1.XMLLicenseService.XmlLicenseServiceSoap {
        
        public XmlLicenseServiceSoapClient() {
        }
        
        public XmlLicenseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlLicenseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlLicenseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlLicenseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode UpdateCheck(System.Xml.XmlNode xml) {
            return base.Channel.UpdateCheck(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateCheckAsync(System.Xml.XmlNode xml) {
            return base.Channel.UpdateCheckAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateCheckS(string xml) {
            return base.Channel.UpdateCheckS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateCheckSAsync(string xml) {
            return base.Channel.UpdateCheckSAsync(xml);
        }
        
        public System.Xml.XmlNode InfoCheck(System.Xml.XmlNode xml) {
            return base.Channel.InfoCheck(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InfoCheckAsync(System.Xml.XmlNode xml) {
            return base.Channel.InfoCheckAsync(xml);
        }
        
        public System.Xml.XmlNode InfoCheckS(string xml) {
            return base.Channel.InfoCheckS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InfoCheckSAsync(string xml) {
            return base.Channel.InfoCheckSAsync(xml);
        }
        
        public System.Xml.XmlNode ValidateRegistration(System.Xml.XmlNode xml) {
            return base.Channel.ValidateRegistration(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValidateRegistrationAsync(System.Xml.XmlNode xml) {
            return base.Channel.ValidateRegistrationAsync(xml);
        }
        
        public System.Xml.XmlNode ValidateRegistrationS(string xml) {
            return base.Channel.ValidateRegistrationS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ValidateRegistrationSAsync(string xml) {
            return base.Channel.ValidateRegistrationSAsync(xml);
        }
        
        public System.Xml.XmlNode Register(System.Xml.XmlNode xml) {
            return base.Channel.Register(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RegisterAsync(System.Xml.XmlNode xml) {
            return base.Channel.RegisterAsync(xml);
        }
        
        public System.Xml.XmlNode RegisterS(string xml) {
            return base.Channel.RegisterS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RegisterSAsync(string xml) {
            return base.Channel.RegisterSAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateRegistration(System.Xml.XmlNode xml) {
            return base.Channel.UpdateRegistration(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateRegistrationAsync(System.Xml.XmlNode xml) {
            return base.Channel.UpdateRegistrationAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateRegistrationS(string xml) {
            return base.Channel.UpdateRegistrationS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateRegistrationSAsync(string xml) {
            return base.Channel.UpdateRegistrationSAsync(xml);
        }
        
        public System.Xml.XmlNode Add(System.Xml.XmlNode xml) {
            return base.Channel.Add(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAsync(System.Xml.XmlNode xml) {
            return base.Channel.AddAsync(xml);
        }
        
        public System.Xml.XmlNode AddS(string xml) {
            return base.Channel.AddS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddSAsync(string xml) {
            return base.Channel.AddSAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateActivationFields(string xml) {
            return base.Channel.UpdateActivationFields(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateActivationFieldsAsync(string xml) {
            return base.Channel.UpdateActivationFieldsAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateUserDefinedFields(System.Xml.XmlNode xml) {
            return base.Channel.UpdateUserDefinedFields(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateUserDefinedFieldsAsync(System.Xml.XmlNode xml) {
            return base.Channel.UpdateUserDefinedFieldsAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateUserDefinedFieldsS(string xml) {
            return base.Channel.UpdateUserDefinedFieldsS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateUserDefinedFieldsSAsync(string xml) {
            return base.Channel.UpdateUserDefinedFieldsSAsync(xml);
        }
        
        public System.Xml.XmlNode GetLicenseCustomData(System.Xml.XmlNode xml) {
            return base.Channel.GetLicenseCustomData(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLicenseCustomDataAsync(System.Xml.XmlNode xml) {
            return base.Channel.GetLicenseCustomDataAsync(xml);
        }
        
        public System.Xml.XmlNode GetLicenseCustomDataS(string xml) {
            return base.Channel.GetLicenseCustomDataS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLicenseCustomDataSAsync(string xml) {
            return base.Channel.GetLicenseCustomDataSAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateLicenseCustomData(System.Xml.XmlNode xml) {
            return base.Channel.UpdateLicenseCustomData(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateLicenseCustomDataAsync(System.Xml.XmlNode xml) {
            return base.Channel.UpdateLicenseCustomDataAsync(xml);
        }
        
        public System.Xml.XmlNode UpdateLicenseCustomDataS(string xml) {
            return base.Channel.UpdateLicenseCustomDataS(xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> UpdateLicenseCustomDataSAsync(string xml) {
            return base.Channel.UpdateLicenseCustomDataSAsync(xml);
        }
    }
}
